# Generated by Django 5.2.12 on 2026-03-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptlog',
            name='adoption_ratio',
        ),
    ]
