# Generated by Django 5.2.12 on 2026-03-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_promptlog_adoption_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='adoption_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='aiq_p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='final_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
