# Generated by Django 5.2.12 on 2026-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promptlog_adoption_ratio_studenttask_aiq_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
