# Generated by Django 5.2.12 on 2026-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studenttask_session_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='aiq_p2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
