# Generated by Django 5.2.12 on 2026-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studenttask_aiq_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='aiq_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
