# Generated by Django 5.2.12 on 2026-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studenttask_aiq_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='aiq_p5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
