# Generated by Django 5.2.12 on 2026-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studenttask_aiq_p5'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='prompt_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
