# Generated by Django 5.2.12 on 2026-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_promptlog_prompt_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='aiq_p3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='aiq_p4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
